import 'dotenv/config'
import { hashPassword } from './auth.js'
import { connectDatabase, disconnectDatabase } from './db.js'
import { Lesson, type LessonDocument } from './models/lesson.js'
import { Quiz, type QuizDocument } from './models/quiz.js'
import { User } from './models/user.js'

const lessons: LessonDocument[] = [
  {
    slug: 'sky-blue',
    category: 'Science',
    title: 'Why is the sky blue?',
    topic: 'Light scattering',
    explanation: 'Air molecules scatter short blue wavelengths of sunlight more strongly than long red wavelengths, spreading blue light across the daytime sky.',
    takeaway: 'Blue light gets scattered most by the atmosphere.',
    difficulty: 'Beginner',
    visualKey: 'prism',
    relatedTopics: ['light', 'atmosphere', 'color'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    status: 'approved',
    questions: [
      { id: 'q1', question: 'Which light scatters most in the atmosphere?', options: ['Red', 'Blue', 'Green', 'Infrared'], answer: 1, explanation: 'Short blue wavelengths are scattered more strongly by air molecules.' },
      { id: 'q2', question: 'What causes Rayleigh scattering?', options: ['Cloud moisture', 'Atmospheric gas molecules', 'Dust particles', 'Solar flares'], answer: 1, explanation: 'Gas molecules in the atmosphere scatter shorter blue light waves.' }
    ]
  },
  {
    slug: 'vaccines-memory',
    category: 'Science',
    title: 'How vaccines train immunity',
    topic: 'Immune memory',
    explanation: 'A vaccine safely shows the immune system a recognizable feature of a pathogen, allowing memory cells to respond faster during a later encounter.',
    takeaway: 'Immune memory makes a second response faster and stronger.',
    difficulty: 'Beginner',
    visualKey: 'shield',
    relatedTopics: ['cells', 'health', 'biology'],
    mediaType: 'text',
    status: 'approved',
    questions: [
      { id: 'q1', question: 'What cell type creates long-term immunity?', options: ['Red blood cells', 'Memory cells', 'Platelets', 'Hormones'], answer: 1, explanation: 'Memory B and T cells remember pathogens for rapid future responses.' }
    ]
  },
  {
    slug: 'planes-fly',
    category: 'Science',
    title: 'Why planes can fly',
    topic: 'Lift',
    explanation: 'A wing changes the airflow around it, creating a pressure difference and redirecting air downward. The matching upward force is lift.',
    takeaway: 'Lift is the upward force created by a wing moving through air.',
    difficulty: 'Beginner',
    visualKey: 'wing',
    relatedTopics: ['forces', 'motion', 'engineering'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    status: 'approved',
    questions: [
      { id: 'q1', question: 'What force pushes an airplane upward?', options: ['Thrust', 'Drag', 'Lift', 'Gravity'], answer: 2, explanation: 'Lift is generated by wing shape and forward airflow velocity.' }
    ]
  },
  {
    slug: 'black-holes',
    category: 'Space',
    title: 'How black holes work',
    topic: 'Gravity',
    explanation: 'When enough mass is compressed into a small space, gravity becomes so strong that beyond the event horizon even light cannot escape.',
    takeaway: 'A black hole is defined by an escape boundary, not by being a cosmic vacuum.',
    difficulty: 'Intermediate',
    visualKey: 'orbit',
    relatedTopics: ['gravity', 'stars', 'space-time'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    status: 'approved',
    questions: [
      { id: 'q1', question: 'What marks the point beyond which light cannot escape?', options: ['The core', 'The orbit', 'The event horizon', 'The accretion disk'], answer: 2, explanation: 'The event horizon is the boundary around a black hole where escape is no longer possible.' }
    ]
  },
  {
    slug: 'binary',
    category: 'Technology',
    title: 'Why computers use binary',
    topic: 'Binary numbers',
    explanation: 'Electronic circuits can reliably distinguish two voltage states, so computers represent information with combinations of 0 and 1.',
    takeaway: 'Binary fits the two stable states of digital circuits.',
    difficulty: 'Beginner',
    visualKey: 'code',
    relatedTopics: ['logic', 'circuits', 'data'],
    mediaType: 'text',
    status: 'approved',
    questions: [
      { id: 'q1', question: 'Why do digital circuits use binary?', options: ['It is cheaper', 'Two voltage states are very reliable', 'It uses less power', 'Math is faster'], answer: 1, explanation: 'High and low voltage states are easily distinguished without noise.' }
    ]
  },
  {
    slug: 'compound-interest',
    category: 'Mathematics',
    title: 'Why compound interest matters',
    topic: 'Exponential growth',
    explanation: 'Compound interest adds growth to the original amount and to earlier growth, so the base gets larger over time.',
    takeaway: 'Growth can accelerate when each period builds on the last.',
    difficulty: 'Beginner',
    visualKey: 'growth',
    relatedTopics: ['money', 'percentages', 'planning'],
    mediaType: 'text',
    status: 'approved',
    questions: [
      { id: 'q1', question: 'What does compound growth build on?', options: ['Only the original amount', 'Earlier growth as well as original', 'A fixed fee', 'Random rate'], answer: 1, explanation: 'Compound growth accumulates on top of accumulated interest.' }
    ]
  },
  {
    slug: 'spacing-effect',
    category: 'Psychology',
    title: 'Why spaced practice works',
    topic: 'Spacing effect',
    explanation: 'Reviewing information across separate sessions gives memory repeated chances to retrieve and rebuild the idea.',
    takeaway: 'Short, spread-out reviews usually beat one long cram session.',
    difficulty: 'Beginner',
    visualKey: 'calendar',
    relatedTopics: ['memory', 'learning', 'habits'],
    mediaType: 'text',
    status: 'approved',
    questions: [
      { id: 'q1', question: 'Which study pattern strengthens memory?', options: ['One long cram session', 'No review', 'Short reviews spread over time', 'Skimming headlines'], answer: 2, explanation: 'Spaced retrieval reinforces synaptic pathways over time.' }
    ]
  },
  {
    slug: 'user-post-quantum',
    category: 'Technology',
    title: 'Quantum Computing in 60 Seconds',
    topic: 'Quantum bits',
    explanation: 'Unlike classical bits that are either 0 or 1, quantum bits (qubits) leverage superposition to represent complex states simultaneously.',
    takeaway: 'Superposition gives quantum computers massive parallel computing power.',
    difficulty: 'Intermediate',
    visualKey: 'spark',
    relatedTopics: ['physics', 'tech', 'computing'],
    mediaType: 'text',
    authorName: 'Alex M.',
    status: 'pending',
    questions: []
  }
]

const demoProfiles = [
  { email: 'alex@bolt.demo', username: 'alexbolt', displayName: 'Alex M.', password: 'BoltDemo123!', interests: ['Space', 'Science', 'Technology'], age: 16, grade: 'Grade 9-12', xp: 1250, streak: 5, completedCount: 12, role: 'user', bio: 'Tech enthusiast & future space engineer 🚀', followers: ['mayabolt', 'sambolt'], following: ['mayabolt'] },
  { email: 'maya@bolt.demo', username: 'mayabolt', displayName: 'Maya R.', password: 'BoltLearn123!', interests: ['Psychology', 'Literature', 'History'], age: 20, grade: 'College / Adult', xp: 2400, streak: 9, completedCount: 22, role: 'user', bio: 'Exploring cognitive science and ancient history 📚', followers: ['alexbolt'], following: ['alexbolt', 'sambolt'] },
  { email: 'sam@bolt.demo', username: 'sambolt', displayName: 'Sam T.', password: 'BoltGreen123!', interests: ['Environment', 'Science', 'Economics'], age: 14, grade: 'Grade 6-8', xp: 850, streak: 3, completedCount: 8, role: 'user', bio: 'Passionate about clean energy and biodiversity 🌱', followers: ['mayabolt'], following: ['alexbolt'] },
  { email: 'admin@bolt.demo', username: 'adminbolt', displayName: 'Admin User', password: 'BoltAdmin123!', interests: ['Science', 'Technology', 'Mathematics'], age: 25, grade: 'College / Adult', xp: 9990, streak: 30, completedCount: 50, role: 'admin', bio: 'Bolt Platform Administrator ⚡', followers: ['alexbolt', 'mayabolt', 'sambolt'], following: [] },
]

const quizzes: QuizDocument[] = [
  { lessonSlug: 'sky-blue', question: 'Which light scatters most in the atmosphere?', options: ['Red', 'Blue', 'Green', 'Infrared'], answer: 1, explanation: 'Short blue wavelengths are scattered more strongly by air molecules.' },
  { lessonSlug: 'black-holes', question: 'What marks the point beyond which light cannot escape?', options: ['The core', 'The orbit', 'The event horizon', 'The accretion disk'], answer: 2, explanation: 'The event horizon is the boundary around a black hole where escape is no longer possible.' },
  { lessonSlug: 'planes-fly', question: 'What force pushes an airplane upward?', options: ['Thrust', 'Drag', 'Lift', 'Gravity'], answer: 2, explanation: 'Lift is generated by wing shape and forward airflow velocity.' },
  { lessonSlug: 'compound-interest', question: 'What does compound growth build on?', options: ['Only the original amount', 'Earlier growth as well as the original', 'A fixed fee', 'A random rate'], answer: 1, explanation: 'Each period adds growth to the amount that has already grown.' },
  { lessonSlug: 'spacing-effect', question: 'Which study pattern usually strengthens memory?', options: ['One long cram session', 'No review', 'Short reviews spread over time', 'Reading only the title'], answer: 2, explanation: 'Spaced practice gives memory repeated retrieval opportunities.' },
]

await connectDatabase()
await Lesson.deleteMany({})
await Lesson.insertMany(lessons)
console.log(`Seeded ${lessons.length} lessons`)
await Quiz.deleteMany({})
await Quiz.insertMany(quizzes)
console.log(`Seeded ${quizzes.length} quizzes`)
await User.deleteMany({ email: { $in: demoProfiles.map((profile) => profile.email) } })
await User.insertMany(await Promise.all(demoProfiles.map(async (profile) => ({
  email: profile.email,
  username: profile.username,
  displayName: profile.displayName,
  passwordHash: await hashPassword(profile.password),
  interests: profile.interests,
  age: profile.age,
  grade: profile.grade,
  xp: profile.xp,
  streak: profile.streak,
  completedCount: profile.completedCount,
  role: profile.role as 'user' | 'admin',
  bio: profile.bio,
  avatar: '',
  followers: profile.followers,
  following: profile.following,
}))))
console.log(`Seeded ${demoProfiles.length} demo profiles`)
await disconnectDatabase()