import 'dotenv/config'
import { hashPassword } from './auth.js'
import { connectDatabase, disconnectDatabase } from './db.js'
import { Lesson, type LessonDocument } from './models/lesson.js'
import { Quiz, type QuizDocument } from './models/quiz.js'
import { User } from './models/user.js'

const lessons: LessonDocument[] = [
  {
    slug: 'sky-blue',
    category: 'Science',
    title: 'Why is the sky blue?',
    topic: 'Light scattering',
    explanation: 'Sunlight contains every color. When it enters the atmosphere, nitrogen and oxygen molecules scatter shorter blue wavelengths far more than longer red ones — a process called Rayleigh scattering. This scattered blue light reaches your eyes from every direction, painting the sky blue during the day.',
    takeaway: 'Blue light gets scattered most by atmospheric molecules.',
    difficulty: 'Beginner',
    visualKey: 'prism',
    relatedTopics: ['light', 'atmosphere', 'color'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    status: 'approved',
    minAge: 6, maxAge: 99,
    questions: [
      { id: 'q1', question: 'Which color of light scatters most in the atmosphere?', options: ['Red', 'Blue', 'Green', 'Infrared'], answer: 1, explanation: 'Short blue wavelengths are scattered more strongly by air molecules.' },
      { id: 'q2', question: 'What causes Rayleigh scattering?', options: ['Cloud moisture', 'Atmospheric gas molecules', 'Dust particles', 'Solar flares'], answer: 1, explanation: 'Gas molecules in the atmosphere scatter shorter blue light waves.' },
      { id: 'q3', question: 'Why does the sky turn red at sunset?', options: ['Sun produces red light at night', 'Blue light is absorbed by clouds', 'Sunlight passes through more atmosphere, scattering away blue', 'The ozone layer filters blue light'], answer: 2, explanation: 'At sunset the longer path scatters away most blue light, leaving red and orange.' },
    ]
  },
  {
    slug: 'vaccines-memory',
    category: 'Science',
    title: 'How vaccines train your immune system',
    topic: 'Immune memory',
    explanation: 'Vaccines introduce a harmless piece of a pathogen — a weakened virus, a protein fragment, or genetic instructions. Your immune system learns to recognize this invader and creates memory B and T cells. If the real pathogen arrives later, these memory cells mount a rapid defense before you get seriously ill.',
    takeaway: 'Immune memory lets your body respond faster to threats it has seen before.',
    difficulty: 'Beginner',
    visualKey: 'shield',
    relatedTopics: ['cells', 'health', 'biology'],
    mediaType: 'text',
    status: 'approved',
    minAge: 10, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What cell type creates long-term immunity?', options: ['Red blood cells', 'Memory B and T cells', 'Platelets', 'Skin cells'], answer: 1, explanation: 'Memory B and T cells remember pathogens for rapid future responses.' },
      { id: 'q2', question: 'What does a vaccine introduce to the body?', options: ['Full-strength virus', 'Antibiotics', 'Harmless pathogen fragments', 'White blood cells'], answer: 2, explanation: 'Vaccines use weakened or partial pathogen material to train the immune system safely.' },
      { id: 'q3', question: 'Why is the second immune response faster?', options: ['Fever runs higher', 'Memory cells are already prepared', 'Antibiotics help', 'Blood flows faster'], answer: 1, explanation: 'Memory cells from the first exposure rapidly produce antibodies on re-encounter.' },
    ]
  },
  {
    slug: 'planes-fly',
    category: 'Science',
    title: 'The physics behind flight',
    topic: 'Lift and aerodynamics',
    explanation: 'A wing is shaped so air moves faster over the top than below. By Bernoulli\'s principle, faster air has lower pressure, creating an upward pressure difference called lift. Meanwhile the wing also deflects air downward — Newton\'s third law pushes the wing up. Both effects combine to keep a plane airborne.',
    takeaway: 'Lift comes from pressure differences and momentum exchange with the air.',
    difficulty: 'Beginner',
    visualKey: 'wing',
    relatedTopics: ['forces', 'motion', 'engineering'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    status: 'approved',
    minAge: 8, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What force pushes an airplane upward?', options: ['Thrust', 'Drag', 'Lift', 'Gravity'], answer: 2, explanation: 'Lift is generated by wing shape and forward airflow velocity.' },
      { id: 'q2', question: 'Which principle explains lower pressure above a wing?', options: ['Archimedes', 'Bernoulli', 'Newton first law', 'Ohm'], answer: 1, explanation: 'Bernoulli\'s principle states faster fluid flow creates lower pressure.' },
      { id: 'q3', question: 'What are the four forces acting on an airplane?', options: ['Lift, weight, thrust, drag', 'Push, pull, spin, stop', 'Gravity, friction, tension, torque', 'Speed, altitude, direction, fuel'], answer: 0, explanation: 'Lift, weight (gravity), thrust, and drag are the four aerodynamic forces.' },
    ]
  },
  {
    slug: 'black-holes',
    category: 'Space',
    title: 'Black holes: nature\'s ultimate gravity trap',
    topic: 'Gravity and spacetime',
    explanation: 'When a massive star collapses, it can compress its core so tightly that the escape velocity exceeds the speed of light. The boundary where this happens is the event horizon. Beyond it, nothing — not even light — can escape. Inside, our current physics breaks down at a point called the singularity.',
    takeaway: 'A black hole is defined by its event horizon, not by being a cosmic vacuum cleaner.',
    difficulty: 'Intermediate',
    visualKey: 'orbit',
    relatedTopics: ['gravity', 'stars', 'space-time'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    status: 'approved',
    minAge: 12, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What marks the boundary where light cannot escape?', options: ['The core', 'The orbit', 'The event horizon', 'The accretion disk'], answer: 2, explanation: 'The event horizon is the boundary around a black hole where escape velocity exceeds the speed of light.' },
      { id: 'q2', question: 'What happens at the singularity?', options: ['Time stops', 'Known physics breaks down', 'Light reverses', 'Temperature reaches absolute zero'], answer: 1, explanation: 'At the singularity, density becomes infinite and our physical theories cannot predict outcomes.' },
      { id: 'q3', question: 'How are stellar black holes formed?', options: ['By asteroid collisions', 'By supernova collapse of massive stars', 'By galaxy mergers only', 'By dark energy'], answer: 1, explanation: 'Massive stars that exhaust their fuel undergo core collapse, sometimes forming black holes.' },
    ]
  },
  {
    slug: 'binary',
    category: 'Technology',
    title: 'Why computers speak in 0s and 1s',
    topic: 'Binary and digital logic',
    explanation: 'Electronic transistors work like tiny switches — on or off, high voltage or low. Using just two states makes circuits extremely reliable because there is a wide margin between "definitely on" and "definitely off." Every photo, video, and app on your device ultimately reduces to patterns of these binary digits.',
    takeaway: 'Binary is perfect for electronics because two clear voltage states resist noise.',
    difficulty: 'Beginner',
    visualKey: 'code',
    relatedTopics: ['logic', 'circuits', 'data'],
    mediaType: 'text',
    status: 'approved',
    minAge: 8, maxAge: 99,
    questions: [
      { id: 'q1', question: 'Why do digital circuits use binary?', options: ['It is cheaper', 'Two voltage states are very reliable', 'It uses less power', 'Math works faster'], answer: 1, explanation: 'High and low voltage states are easily distinguished even with electronic noise.' },
      { id: 'q2', question: 'How many bits make one byte?', options: ['4', '8', '16', '2'], answer: 1, explanation: 'One byte consists of 8 bits, allowing 256 different values.' },
      { id: 'q3', question: 'What does a transistor act as in a computer?', options: ['A battery', 'A tiny switch', 'A speaker', 'A sensor'], answer: 1, explanation: 'Transistors switch between on and off states to process binary information.' },
    ]
  },
  {
    slug: 'compound-interest',
    category: 'Mathematics',
    title: 'The magic of compound interest',
    topic: 'Exponential growth',
    explanation: 'When interest is calculated on both the principal and previously earned interest, your money grows exponentially instead of linearly. Albert Einstein reportedly called it the eighth wonder of the world. Over decades, even small regular investments can grow into substantial wealth thanks to compounding.',
    takeaway: 'Growth accelerates when each period builds on accumulated results.',
    difficulty: 'Beginner',
    visualKey: 'growth',
    relatedTopics: ['money', 'percentages', 'planning'],
    mediaType: 'text',
    status: 'approved',
    minAge: 12, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What does compound interest grow on?', options: ['Only the original amount', 'The original plus previously earned interest', 'A fixed annual fee', 'A random rate each year'], answer: 1, explanation: 'Compound interest accumulates on top of accumulated interest.' },
      { id: 'q2', question: 'If you invest $1000 at 10% compound interest, roughly how much after 7 years?', options: ['$1700', '$2000', '$1400', '$1100'], answer: 1, explanation: 'The Rule of 72 estimates doubling time: 72/10 = about 7.2 years, so roughly $2000.' },
    ]
  },
  {
    slug: 'spacing-effect',
    category: 'Psychology',
    title: 'Why cramming fails: the spacing effect',
    topic: 'Memory and learning',
    explanation: 'Reviewing material in spaced sessions forces your brain to actively retrieve information, strengthening neural pathways each time. Massed practice (cramming) feels productive but leads to faster forgetting. Studies show that distributing study over days or weeks produces dramatically better long-term retention.',
    takeaway: 'Short, spread-out review sessions beat one long cramming marathon.',
    difficulty: 'Beginner',
    visualKey: 'calendar',
    relatedTopics: ['memory', 'learning', 'habits'],
    mediaType: 'text',
    status: 'approved',
    minAge: 10, maxAge: 99,
    questions: [
      { id: 'q1', question: 'Which study pattern strengthens long-term memory?', options: ['One long cram session', 'No review at all', 'Short reviews spread over time', 'Skimming headlines quickly'], answer: 2, explanation: 'Spaced retrieval reinforces synaptic pathways over time.' },
      { id: 'q2', question: 'Why does cramming feel effective even though it is not?', options: ['It genuinely works', 'Short-term recall is high but fades fast', 'Teachers recommend it', 'It triggers deep sleep learning'], answer: 1, explanation: 'Cramming boosts short-term recall, giving a false sense of mastery that quickly decays.' },
    ]
  },
  {
    slug: 'photosynthesis',
    category: 'Science',
    title: 'How plants turn sunlight into food',
    topic: 'Photosynthesis',
    explanation: 'Inside leaf cells, chloroplasts capture light energy and use it to split water molecules. The hydrogen combines with CO2 from the air to build glucose — the plant\'s food. Oxygen is released as a byproduct. This single process is the foundation of nearly all food chains on Earth.',
    takeaway: 'Plants convert light, water, and CO2 into glucose and oxygen.',
    difficulty: 'Beginner',
    visualKey: 'leaf',
    relatedTopics: ['biology', 'energy', 'ecology'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    status: 'approved',
    minAge: 8, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What organelle carries out photosynthesis?', options: ['Mitochondria', 'Chloroplast', 'Nucleus', 'Ribosome'], answer: 1, explanation: 'Chloroplasts contain chlorophyll and are the site of photosynthesis.' },
      { id: 'q2', question: 'What gas is released during photosynthesis?', options: ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Hydrogen'], answer: 2, explanation: 'Oxygen is a byproduct when water molecules are split during the light reactions.' },
      { id: 'q3', question: 'What are the raw materials of photosynthesis?', options: ['Glucose and oxygen', 'Water, CO2, and light energy', 'Protein and fat', 'ATP and NADPH'], answer: 1, explanation: 'Plants use water, carbon dioxide, and sunlight to produce glucose.' },
    ]
  },
  {
    slug: 'ocean-currents',
    category: 'Environment',
    title: 'Ocean currents: Earth\'s hidden climate engine',
    topic: 'Thermohaline circulation',
    explanation: 'Ocean currents move heat from the equator toward the poles. The "global conveyor belt" is driven by differences in water temperature and salinity. Warm surface water flows poleward, cools, becomes denser, sinks, and returns along the deep ocean floor — a cycle that takes roughly 1000 years to complete.',
    takeaway: 'Ocean currents redistribute heat globally, regulating climate patterns.',
    difficulty: 'Intermediate',
    visualKey: 'wave',
    relatedTopics: ['climate', 'geography', 'water'],
    mediaType: 'text',
    status: 'approved',
    minAge: 12, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What drives the global conveyor belt?', options: ['Wind only', 'Differences in temperature and salinity', 'Tidal gravity', 'Volcanic heat'], answer: 1, explanation: 'Thermohaline circulation is driven by density differences caused by temperature and salt content.' },
      { id: 'q2', question: 'How long does one full ocean conveyor belt cycle take?', options: ['1 year', '100 years', 'About 1000 years', '1 million years'], answer: 2, explanation: 'The deep ocean thermohaline cycle takes roughly 1000 years to complete.' },
    ]
  },
  {
    slug: 'dna-code',
    category: 'Science',
    title: 'DNA: the code of life',
    topic: 'Genetics basics',
    explanation: 'DNA is a double-helix molecule made of four nucleotide bases: adenine (A), thymine (T), guanine (G), and cytosine (C). These bases pair specifically — A with T, G with C — creating a code that instructs cells how to build proteins. Your entire body plan is written in roughly 3 billion of these base pairs.',
    takeaway: 'Four molecular letters encode all the instructions to build and run a living organism.',
    difficulty: 'Beginner',
    visualKey: 'helix',
    relatedTopics: ['biology', 'genetics', 'evolution'],
    mediaType: 'text',
    status: 'approved',
    minAge: 10, maxAge: 99,
    questions: [
      { id: 'q1', question: 'Which bases pair together in DNA?', options: ['A-G and T-C', 'A-T and G-C', 'A-C and G-T', 'All pair randomly'], answer: 1, explanation: 'Adenine pairs with thymine, guanine pairs with cytosine.' },
      { id: 'q2', question: 'Roughly how many base pairs are in the human genome?', options: ['3 million', '3 billion', '300 million', '30 billion'], answer: 1, explanation: 'The human genome contains approximately 3 billion base pairs.' },
      { id: 'q3', question: 'What shape is the DNA molecule?', options: ['Straight line', 'Single loop', 'Double helix', 'Flat sheet'], answer: 2, explanation: 'Watson and Crick discovered that DNA forms a double helix structure.' },
    ]
  },
  {
    slug: 'gravity-explained',
    category: 'Science',
    title: 'What is gravity, really?',
    topic: 'General relativity',
    explanation: 'Newton described gravity as a force between masses. Einstein went further: gravity is actually the curvature of spacetime caused by mass and energy. Massive objects like stars and planets warp the fabric of space around them, and other objects follow curved paths through this warped geometry.',
    takeaway: 'Mass warps spacetime, and gravity is how we experience that curvature.',
    difficulty: 'Intermediate',
    visualKey: 'orbit',
    relatedTopics: ['physics', 'space', 'relativity'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    status: 'approved',
    minAge: 12, maxAge: 99,
    questions: [
      { id: 'q1', question: 'How did Einstein describe gravity?', options: ['An invisible string', 'Curvature of spacetime by mass', 'Magnetic attraction', 'Quantum tunneling'], answer: 1, explanation: 'General relativity describes gravity as the warping of spacetime by mass and energy.' },
      { id: 'q2', question: 'Who first described gravity as a force between masses?', options: ['Galileo', 'Einstein', 'Newton', 'Kepler'], answer: 2, explanation: 'Isaac Newton formulated the law of universal gravitation in 1687.' },
    ]
  },
  {
    slug: 'ai-neural-nets',
    category: 'Technology',
    title: 'How neural networks learn',
    topic: 'Machine learning basics',
    explanation: 'Artificial neural networks are layers of connected nodes loosely inspired by brain neurons. Data flows through input layers, gets transformed by hidden layers with adjustable weights, and produces an output. During training, the network compares its output to the correct answer and adjusts its weights to reduce the error — a process called backpropagation.',
    takeaway: 'Neural networks learn by repeatedly adjusting connection weights to minimize errors.',
    difficulty: 'Intermediate',
    visualKey: 'network',
    relatedTopics: ['ai', 'data', 'algorithms'],
    mediaType: 'text',
    status: 'approved',
    minAge: 14, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What is backpropagation?', options: ['Sending data backwards', 'Adjusting weights based on errors', 'Deleting old data', 'Reversing the network'], answer: 1, explanation: 'Backpropagation calculates error gradients and updates weights from output to input layers.' },
      { id: 'q2', question: 'What are the adjustable parameters in a neural network?', options: ['Data points', 'Weights and biases', 'File sizes', 'Pixel colors'], answer: 1, explanation: 'Weights and biases are the learnable parameters that get tuned during training.' },
      { id: 'q3', question: 'What are hidden layers?', options: ['Encrypted data', 'Layers between input and output that transform data', 'Secret passwords', 'Backup storage'], answer: 1, explanation: 'Hidden layers perform nonlinear transformations that enable the network to learn complex patterns.' },
    ]
  },
  {
    slug: 'sleep-science',
    category: 'Psychology',
    title: 'Why your brain needs sleep',
    topic: 'Sleep and memory consolidation',
    explanation: 'During sleep, your brain replays the day\'s experiences, strengthening important neural connections and pruning weak ones. The glymphatic system also flushes out metabolic waste products. Missing sleep impairs memory consolidation, emotional regulation, and immune function — even one night of poor sleep measurably reduces cognitive performance.',
    takeaway: 'Sleep is when your brain consolidates memories and clears metabolic waste.',
    difficulty: 'Beginner',
    visualKey: 'moon',
    relatedTopics: ['health', 'brain', 'memory'],
    mediaType: 'text',
    status: 'approved',
    minAge: 8, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What system clears brain waste during sleep?', options: ['Lymphatic', 'Circulatory', 'Glymphatic', 'Digestive'], answer: 2, explanation: 'The glymphatic system flushes metabolic waste from the brain during sleep.' },
      { id: 'q2', question: 'What happens to memories during sleep?', options: ['They are deleted', 'They are consolidated and strengthened', 'They move to the liver', 'Nothing changes'], answer: 1, explanation: 'Sleep allows the brain to replay and strengthen important neural pathways.' },
    ]
  },
  {
    slug: 'climate-change',
    category: 'Environment',
    title: 'The greenhouse effect explained',
    topic: 'Climate science',
    explanation: 'Earth\'s atmosphere contains greenhouse gases like CO2, methane, and water vapor. Sunlight warms the surface, which radiates heat as infrared radiation. Greenhouse gases trap some of this heat, warming the planet enough to support life. But burning fossil fuels has increased CO2 levels by 50% since the Industrial Revolution, trapping more heat and raising global temperatures.',
    takeaway: 'The greenhouse effect is natural and essential, but human emissions are amplifying it dangerously.',
    difficulty: 'Beginner',
    visualKey: 'earth',
    relatedTopics: ['climate', 'energy', 'atmosphere'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    status: 'approved',
    minAge: 10, maxAge: 99,
    questions: [
      { id: 'q1', question: 'Which gas is the primary driver of human-caused climate change?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'], answer: 2, explanation: 'CO2 from fossil fuel burning is the largest contributor to enhanced greenhouse warming.' },
      { id: 'q2', question: 'By how much has CO2 increased since the Industrial Revolution?', options: ['5%', '50%', '200%', '1%'], answer: 1, explanation: 'Atmospheric CO2 has risen about 50% from roughly 280 to over 420 parts per million.' },
      { id: 'q3', question: 'What type of radiation do greenhouse gases trap?', options: ['Ultraviolet', 'Visible light', 'Infrared', 'X-rays'], answer: 2, explanation: 'Greenhouse gases absorb and re-emit infrared (heat) radiation from Earth\'s surface.' },
    ]
  },
  {
    slug: 'mars-colonization',
    category: 'Space',
    title: 'The challenges of living on Mars',
    topic: 'Space colonization',
    explanation: 'Mars has only 38% of Earth\'s gravity, a thin CO2 atmosphere with almost no oxygen, average temperatures of -60°C, and no magnetic field to block radiation. Colonists would need pressurized habitats, radiation shielding, water extraction from subsurface ice, and either hydroponic farming or supply runs from Earth that take 6-9 months each way.',
    takeaway: 'Mars colonization requires solving radiation, food, water, and atmospheric challenges simultaneously.',
    difficulty: 'Intermediate',
    visualKey: 'planet',
    relatedTopics: ['space', 'engineering', 'survival'],
    mediaType: 'text',
    status: 'approved',
    minAge: 12, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What percentage of Earth\'s gravity does Mars have?', options: ['10%', '38%', '75%', '90%'], answer: 1, explanation: 'Mars gravity is about 38% of Earth\'s, meaning you\'d weigh about a third of your Earth weight.' },
      { id: 'q2', question: 'Why is radiation a major concern on Mars?', options: ['Too much oxygen', 'No magnetic field to block cosmic radiation', 'Mars is too close to the sun', 'The soil is radioactive'], answer: 1, explanation: 'Without a strong magnetic field or thick atmosphere, Mars surface is exposed to harmful cosmic and solar radiation.' },
    ]
  },
  {
    slug: 'encryption-basics',
    category: 'Technology',
    title: 'How encryption keeps your data safe',
    topic: 'Cryptography',
    explanation: 'Encryption transforms readable data (plaintext) into scrambled data (ciphertext) using a mathematical key. Only someone with the correct decryption key can reverse the process. Modern encryption like AES uses keys so complex that brute-force cracking would take billions of years, even with today\'s most powerful computers.',
    takeaway: 'Encryption scrambles data with math so only the right key holder can read it.',
    difficulty: 'Intermediate',
    visualKey: 'lock',
    relatedTopics: ['security', 'math', 'privacy'],
    mediaType: 'text',
    status: 'approved',
    minAge: 14, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What is ciphertext?', options: ['A type of font', 'Encrypted scrambled data', 'A programming language', 'A network protocol'], answer: 1, explanation: 'Ciphertext is data that has been encrypted and appears scrambled without the decryption key.' },
      { id: 'q2', question: 'What makes AES encryption strong?', options: ['Short passwords', 'Key complexity that requires billions of years to brute force', 'It uses only letters', 'It deletes data after use'], answer: 1, explanation: 'AES uses 128 to 256-bit keys with astronomical numbers of possible combinations.' },
    ]
  },
  {
    slug: 'pythagorean-theorem',
    category: 'Mathematics',
    title: 'The Pythagorean theorem in everyday life',
    topic: 'Geometry and right triangles',
    explanation: 'In any right triangle, the square of the hypotenuse equals the sum of the squares of the other two sides: a² + b² = c². This 2500-year-old theorem is used daily in construction (ensuring corners are square), navigation (calculating distances), and computer graphics (measuring pixel distances on screen).',
    takeaway: 'a² + b² = c² connects geometry to countless real-world applications.',
    difficulty: 'Beginner',
    visualKey: 'triangle',
    relatedTopics: ['geometry', 'algebra', 'applied math'],
    mediaType: 'text',
    status: 'approved',
    minAge: 10, maxAge: 99,
    questions: [
      { id: 'q1', question: 'In a right triangle with legs 3 and 4, what is the hypotenuse?', options: ['7', '5', '6', '12'], answer: 1, explanation: '3² + 4² = 9 + 16 = 25, and √25 = 5.' },
      { id: 'q2', question: 'Which side is the hypotenuse?', options: ['The shortest side', 'The side opposite the right angle', 'Any vertical side', 'The base'], answer: 1, explanation: 'The hypotenuse is always the longest side, opposite the 90-degree angle.' },
    ]
  },
  {
    slug: 'roman-empire-fall',
    category: 'History',
    title: 'Why the Roman Empire collapsed',
    topic: 'Historical decline',
    explanation: 'The Western Roman Empire didn\'t fall from one cause but from a cascade of interconnected problems: overextended borders requiring huge military spending, political instability with over 20 emperors in 75 years, economic inflation from debased currency, migration pressures from Germanic tribes, and a plague that killed millions. The final emperor, Romulus Augustulus, was deposed in 476 CE.',
    takeaway: 'Complex systems fail through cascading weaknesses, not a single cause.',
    difficulty: 'Intermediate',
    visualKey: 'column',
    relatedTopics: ['civilization', 'politics', 'economics'],
    mediaType: 'text',
    status: 'approved',
    minAge: 12, maxAge: 99,
    questions: [
      { id: 'q1', question: 'When was the last Western Roman Emperor deposed?', options: ['44 BCE', '476 CE', '1066 CE', '1453 CE'], answer: 1, explanation: 'Romulus Augustulus was deposed by Odoacer in 476 CE, traditionally marking the fall.' },
      { id: 'q2', question: 'What was a major economic problem for late Rome?', options: ['Too much gold', 'Currency debasement causing inflation', 'No trade routes', 'Excessive technological change'], answer: 1, explanation: 'Roman rulers debased silver coins, reducing their precious metal content and causing inflation.' },
    ]
  },
  {
    slug: 'water-cycle',
    category: 'Science',
    title: 'The journey of a water droplet',
    topic: 'Water cycle',
    explanation: 'Water continuously moves through Earth\'s systems. The sun heats surface water, causing evaporation into vapor. Rising air cools the vapor into clouds (condensation). When droplets grow heavy enough, they fall as precipitation. Water flows through rivers to oceans or seeps into groundwater, and the cycle repeats endlessly.',
    takeaway: 'The water cycle has no beginning or end — water just keeps transforming and moving.',
    difficulty: 'Beginner',
    visualKey: 'drop',
    relatedTopics: ['weather', 'geography', 'ecology'],
    mediaType: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    status: 'approved',
    minAge: 6, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What drives the water cycle?', options: ['The moon', 'Solar energy', 'Wind turbines', 'Ocean tides'], answer: 1, explanation: 'The sun provides the energy that evaporates water and drives atmospheric circulation.' },
      { id: 'q2', question: 'What is condensation?', options: ['Water soaking into soil', 'Water vapor turning back into liquid droplets', 'Ice melting into water', 'Rain hitting the ground'], answer: 1, explanation: 'Condensation occurs when water vapor cools enough to form liquid droplets, creating clouds.' },
    ]
  },
  {
    slug: 'blockchain-simple',
    category: 'Technology',
    title: 'Blockchain explained simply',
    topic: 'Distributed ledger technology',
    explanation: 'A blockchain is a chain of data blocks where each block contains a list of transactions and a cryptographic hash of the previous block. Changing any past block would invalidate all subsequent hashes. Copies are stored across thousands of computers. This makes blockchain data extremely difficult to alter retroactively without detection.',
    takeaway: 'Blockchain achieves trust through cryptographic linking and distributed copies.',
    difficulty: 'Intermediate',
    visualKey: 'chain',
    relatedTopics: ['crypto', 'security', 'databases'],
    mediaType: 'text',
    status: 'approved',
    minAge: 14, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What links each block to the previous one?', options: ['A password', 'A cryptographic hash', 'A URL', 'A serial number'], answer: 1, explanation: 'Each block contains a hash of the previous block, creating an unbreakable chain of data integrity.' },
      { id: 'q2', question: 'Why is blockchain data hard to tamper with?', options: ['Only one copy exists', 'Changing one block invalidates all following blocks and copies exist on thousands of nodes', 'It self-destructs', 'Government regulation'], answer: 1, explanation: 'Altering a past block would break the hash chain and conflict with distributed copies.' },
    ]
  },
  {
    slug: 'evolution-natural-selection',
    category: 'Science',
    title: 'Natural selection: evolution\'s engine',
    topic: 'Evolutionary biology',
    explanation: 'Within any population, individuals vary in their traits. Those with traits better suited to their environment tend to survive longer and reproduce more, passing those beneficial traits to offspring. Over many generations, this differential survival gradually changes the population\'s characteristics — what Darwin called "descent with modification."',
    takeaway: 'Natural selection favors traits that improve survival and reproduction in a given environment.',
    difficulty: 'Beginner',
    visualKey: 'tree',
    relatedTopics: ['biology', 'genetics', 'ecology'],
    mediaType: 'text',
    status: 'approved',
    minAge: 10, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What does natural selection act on?', options: ['Individual effort', 'Heritable variation in traits', 'Technology', 'Weather patterns'], answer: 1, explanation: 'Natural selection acts on heritable trait differences that affect survival and reproduction.' },
      { id: 'q2', question: 'Who proposed the theory of evolution by natural selection?', options: ['Newton', 'Einstein', 'Darwin', 'Mendel'], answer: 2, explanation: 'Charles Darwin published On the Origin of Species in 1859, outlining natural selection.' },
    ]
  },
  {
    slug: 'cognitive-biases',
    category: 'Psychology',
    title: 'Your brain\'s hidden shortcuts: cognitive biases',
    topic: 'Behavioral psychology',
    explanation: 'Cognitive biases are mental shortcuts that helped our ancestors make fast decisions. Confirmation bias makes you favor information supporting existing beliefs. Anchoring bias lets the first number you hear disproportionately influence your judgment. The Dunning-Kruger effect causes beginners to overestimate their skill and experts to underestimate theirs.',
    takeaway: 'Knowing your mental shortcuts helps you think more clearly and make better decisions.',
    difficulty: 'Intermediate',
    visualKey: 'brain',
    relatedTopics: ['thinking', 'decisions', 'behavior'],
    mediaType: 'text',
    status: 'approved',
    minAge: 14, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What is confirmation bias?', options: ['Preferring data that supports your existing beliefs', 'Confirming your email address', 'Double-checking math', 'Asking for a second opinion'], answer: 0, explanation: 'Confirmation bias leads people to seek, interpret, and remember information that confirms what they already believe.' },
      { id: 'q2', question: 'What does the Dunning-Kruger effect describe?', options: ['Experts being overconfident', 'Beginners overestimating their skill level', 'Memory loss with age', 'Fear of public speaking'], answer: 1, explanation: 'People with low competence in an area often lack the knowledge to recognize their own incompetence.' },
    ]
  },
  {
    slug: 'solar-system-scale',
    category: 'Space',
    title: 'The mind-blowing scale of our solar system',
    topic: 'Astronomical distances',
    explanation: 'If the Sun were a basketball, Earth would be a peppercorn 26 meters away. Jupiter would be a walnut 135 meters away. The nearest star, Proxima Centauri, would be another basketball about 6,800 kilometers away. Light from the Sun takes 8 minutes to reach Earth but over 4 years to reach the nearest star.',
    takeaway: 'Space is overwhelmingly vast — even our closest stellar neighbor is incredibly far away.',
    difficulty: 'Beginner',
    visualKey: 'solar',
    relatedTopics: ['astronomy', 'scale', 'light'],
    mediaType: 'text',
    status: 'approved',
    minAge: 8, maxAge: 99,
    questions: [
      { id: 'q1', question: 'How long does sunlight take to reach Earth?', options: ['Instantly', 'About 8 minutes', 'About 1 hour', 'About 4 years'], answer: 1, explanation: 'Light travels at 300,000 km/s and covers the 150 million km to Earth in about 8 minutes 20 seconds.' },
      { id: 'q2', question: 'What is the nearest star to our Sun?', options: ['Sirius', 'Betelgeuse', 'Proxima Centauri', 'Polaris'], answer: 2, explanation: 'Proxima Centauri is about 4.24 light-years from the Sun, the closest known star.' },
    ]
  },
  {
    slug: 'supply-demand',
    category: 'Economics',
    title: 'Supply and demand: why prices change',
    topic: 'Market economics',
    explanation: 'When demand for a product rises but supply stays the same, sellers can charge more — prices go up. When supply increases but demand stays flat, competition pushes prices down. The point where supply and demand curves meet is the equilibrium price. Nearly every price you see is shaped by this fundamental push and pull.',
    takeaway: 'Prices are signals that balance what people want with what is available.',
    difficulty: 'Beginner',
    visualKey: 'chart',
    relatedTopics: ['trade', 'business', 'society'],
    mediaType: 'text',
    status: 'approved',
    minAge: 12, maxAge: 99,
    questions: [
      { id: 'q1', question: 'What happens to price when demand rises and supply stays constant?', options: ['Price drops', 'Price stays the same', 'Price increases', 'Supply also rises automatically'], answer: 2, explanation: 'Higher demand with fixed supply creates scarcity, allowing sellers to charge more.' },
      { id: 'q2', question: 'What is the equilibrium price?', options: ['The cheapest possible price', 'Where supply and demand curves intersect', 'The government-set price', 'The most expensive price'], answer: 1, explanation: 'Equilibrium is the price point where the quantity demanded equals the quantity supplied.' },
    ]
  },
  {
    slug: 'shakespeare-impact',
    category: 'Literature',
    title: 'How Shakespeare shaped the English language',
    topic: 'Literary influence',
    explanation: 'William Shakespeare invented over 1,700 words still used today including "bedroom," "lonely," "generous," and "assassination." He pioneered the soliloquy to reveal characters\' inner thoughts. His plays explored universal themes — ambition, jealousy, love, betrayal — that remain relevant 400 years later, making him the most-performed playwright in history.',
    takeaway: 'Shakespeare didn\'t just write plays — he fundamentally expanded the English language.',
    difficulty: 'Beginner',
    visualKey: 'quill',
    relatedTopics: ['language', 'theater', 'culture'],
    mediaType: 'text',
    status: 'approved',
    minAge: 10, maxAge: 99,
    questions: [
      { id: 'q1', question: 'Approximately how many words did Shakespeare invent?', options: ['50', '500', '1700+', '10000'], answer: 2, explanation: 'Shakespeare coined over 1,700 words including everyday terms we still use.' },
      { id: 'q2', question: 'What is a soliloquy?', options: ['A type of poem', 'A character speaking their thoughts aloud alone on stage', 'A musical score', 'A sword fight'], answer: 1, explanation: 'A soliloquy reveals a character\'s inner thoughts and motives directly to the audience.' },
    ]
  },
  {
    slug: 'user-post-quantum',
    category: 'Technology',
    title: 'Quantum Computing in 60 Seconds',
    topic: 'Quantum bits',
    explanation: 'Unlike classical bits that are either 0 or 1, quantum bits (qubits) leverage superposition to represent complex states simultaneously. When qubits become entangled, measuring one instantly affects the other regardless of distance. This allows quantum computers to explore many solutions at once for certain problems.',
    takeaway: 'Superposition and entanglement give quantum computers massive parallel computing power.',
    difficulty: 'Intermediate',
    visualKey: 'spark',
    relatedTopics: ['physics', 'tech', 'computing'],
    mediaType: 'text',
    authorName: 'Alex M.',
    status: 'pending',
    minAge: 14, maxAge: 99,
    questions: []
  },
]

const demoProfiles = [
  { email: 'admin@bolt.demo', username: 'adminbolt', displayName: 'Bolt Admin', password: 'admin123', interests: ['Science', 'Technology', 'Mathematics'], age: 28, grade: 'General', xp: 9990, streak: 30, completedCount: 50, role: 'admin', bio: 'Lead Platform Administrator', followers: ['alexbolt', 'mayabolt', 'sambolt', 'norabolt'], following: [] },
  { email: 'alex@bolt.demo', username: 'alexbolt', displayName: 'Alex Martin', password: 'BoltDemo123!', interests: ['Space', 'Science', 'Technology'], age: 16, grade: 'Grade 9-12', xp: 2450, streak: 12, completedCount: 18, role: 'user', bio: 'Future aerospace engineer. Love rockets and robotics.', followers: ['mayabolt', 'sambolt', 'linabolt'], following: ['mayabolt', 'adminbolt', 'sambolt'] },
  { email: 'maya@bolt.demo', username: 'mayabolt', displayName: 'Maya Rivera', password: 'BoltLearn123!', interests: ['Psychology', 'Literature', 'History'], age: 20, grade: 'College / Adult', xp: 4800, streak: 21, completedCount: 35, role: 'user', bio: 'Cognitive science major. Books, brains, and ancient history.', followers: ['alexbolt', 'norabolt', 'liambolt'], following: ['alexbolt', 'sambolt', 'adminbolt'] },
  { email: 'sam@bolt.demo', username: 'sambolt', displayName: 'Sam Torres', password: 'BoltGreen123!', interests: ['Environment', 'Science', 'Economics'], age: 14, grade: 'Grade 6-8', xp: 1650, streak: 7, completedCount: 12, role: 'user', bio: 'Climate activist. Biodiversity matters!', followers: ['mayabolt', 'alexbolt'], following: ['alexbolt', 'norabolt'] },
  { email: 'nora@bolt.demo', username: 'norabolt', displayName: 'Nora Kim', password: 'BoltNora123!', interests: ['Mathematics', 'Technology', 'Science'], age: 17, grade: 'Grade 9-12', xp: 3200, streak: 15, completedCount: 24, role: 'user', bio: 'Math olympiad competitor. Coding since age 12.', followers: ['sambolt', 'alexbolt', 'liambolt'], following: ['mayabolt', 'adminbolt'] },
  { email: 'liam@bolt.demo', username: 'liambolt', displayName: 'Liam Chen', password: 'BoltLiam123!', interests: ['History', 'Economics', 'Literature'], age: 22, grade: 'College / Adult', xp: 1900, streak: 4, completedCount: 14, role: 'user', bio: 'History nerd. Economics grad student.', followers: ['mayabolt'], following: ['mayabolt', 'norabolt'] },
  { email: 'lina@bolt.demo', username: 'linabolt', displayName: 'Lina Patel', password: 'BoltLina123!', interests: ['Science', 'Environment', 'Psychology'], age: 11, grade: 'Grade 6-8', xp: 980, streak: 6, completedCount: 9, role: 'user', bio: 'Animal lover and junior scientist.', followers: ['alexbolt'], following: ['alexbolt'] },
  { email: 'omar@bolt.demo', username: 'omarbolt', displayName: 'Omar Hassan', password: 'BoltOmar123!', interests: ['Space', 'Mathematics', 'Technology'], age: 19, grade: 'College / Adult', xp: 2100, streak: 8, completedCount: 16, role: 'user', bio: 'Astrophysics student. Stargazer.', followers: [], following: ['alexbolt', 'norabolt'] },
  { email: 'julia@bolt.demo', username: 'juliabolt', displayName: 'Julia Santos', password: 'BoltJulia123!', interests: ['Psychology', 'Science', 'Economics'], age: 15, grade: 'Grade 9-12', xp: 1400, streak: 5, completedCount: 11, role: 'user', bio: 'Future psychologist. Fascinated by how people think.', followers: [], following: ['mayabolt'] },
  { email: 'kai@bolt.demo', username: 'kaibolt', displayName: 'Kai Nakamura', password: 'BoltKai123!', interests: ['Technology', 'Science', 'Mathematics'], age: 9, grade: 'Grade 3-5', xp: 420, streak: 3, completedCount: 5, role: 'user', bio: 'Young coder. Scratch and Python are my jam!', followers: [], following: [] },
]

const quizzes: QuizDocument[] = [
  { lessonSlug: 'sky-blue', question: 'Which color of light scatters most in the atmosphere?', options: ['Red', 'Blue', 'Green', 'Infrared'], answer: 1, explanation: 'Short blue wavelengths are scattered more strongly by air molecules.' },
  { lessonSlug: 'vaccines-memory', question: 'What cell type creates long-term immunity?', options: ['Red blood cells', 'Memory B and T cells', 'Platelets', 'Skin cells'], answer: 1, explanation: 'Memory B and T cells remember pathogens for rapid future responses.' },
  { lessonSlug: 'planes-fly', question: 'What force pushes an airplane upward?', options: ['Thrust', 'Drag', 'Lift', 'Gravity'], answer: 2, explanation: 'Lift is generated by wing shape and forward airflow velocity.' },
  { lessonSlug: 'black-holes', question: 'What marks the boundary where light cannot escape?', options: ['The core', 'The orbit', 'The event horizon', 'The accretion disk'], answer: 2, explanation: 'The event horizon is the boundary around a black hole where escape velocity exceeds the speed of light.' },
  { lessonSlug: 'binary', question: 'Why do digital circuits use binary?', options: ['It is cheaper', 'Two voltage states are very reliable', 'It uses less power', 'Math works faster'], answer: 1, explanation: 'High and low voltage states are easily distinguished even with electronic noise.' },
  { lessonSlug: 'compound-interest', question: 'What does compound interest grow on?', options: ['Only the original amount', 'The original plus previously earned interest', 'A fixed annual fee', 'A random rate each year'], answer: 1, explanation: 'Compound interest accumulates on top of accumulated interest.' },
  { lessonSlug: 'spacing-effect', question: 'Which study pattern strengthens long-term memory?', options: ['One long cram session', 'No review at all', 'Short reviews spread over time', 'Skimming headlines quickly'], answer: 2, explanation: 'Spaced retrieval reinforces synaptic pathways over time.' },
  { lessonSlug: 'photosynthesis', question: 'What organelle carries out photosynthesis?', options: ['Mitochondria', 'Chloroplast', 'Nucleus', 'Ribosome'], answer: 1, explanation: 'Chloroplasts contain chlorophyll and are the site of photosynthesis.' },
  { lessonSlug: 'ocean-currents', question: 'What drives the global conveyor belt?', options: ['Wind only', 'Differences in temperature and salinity', 'Tidal gravity', 'Volcanic heat'], answer: 1, explanation: 'Thermohaline circulation is driven by density differences caused by temperature and salt content.' },
  { lessonSlug: 'dna-code', question: 'Which bases pair together in DNA?', options: ['A-G and T-C', 'A-T and G-C', 'A-C and G-T', 'All pair randomly'], answer: 1, explanation: 'Adenine pairs with thymine, guanine pairs with cytosine.' },
  { lessonSlug: 'gravity-explained', question: 'How did Einstein describe gravity?', options: ['An invisible string', 'Curvature of spacetime by mass', 'Magnetic attraction', 'Quantum tunneling'], answer: 1, explanation: 'General relativity describes gravity as the warping of spacetime by mass and energy.' },
  { lessonSlug: 'ai-neural-nets', question: 'What is backpropagation?', options: ['Sending data backwards', 'Adjusting weights based on errors', 'Deleting old data', 'Reversing the network'], answer: 1, explanation: 'Backpropagation calculates error gradients and updates weights from output to input layers.' },
  { lessonSlug: 'sleep-science', question: 'What system clears brain waste during sleep?', options: ['Lymphatic', 'Circulatory', 'Glymphatic', 'Digestive'], answer: 2, explanation: 'The glymphatic system flushes metabolic waste from the brain during sleep.' },
  { lessonSlug: 'climate-change', question: 'Which gas is the primary driver of human-caused climate change?', options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium'], answer: 2, explanation: 'CO2 from fossil fuel burning is the largest contributor to enhanced greenhouse warming.' },
  { lessonSlug: 'mars-colonization', question: 'What percentage of Earth\'s gravity does Mars have?', options: ['10%', '38%', '75%', '90%'], answer: 1, explanation: 'Mars gravity is about 38% of Earth\'s.' },
  { lessonSlug: 'encryption-basics', question: 'What is ciphertext?', options: ['A type of font', 'Encrypted scrambled data', 'A programming language', 'A network protocol'], answer: 1, explanation: 'Ciphertext is data that has been encrypted and appears scrambled without the decryption key.' },
  { lessonSlug: 'pythagorean-theorem', question: 'In a right triangle with legs 3 and 4, what is the hypotenuse?', options: ['7', '5', '6', '12'], answer: 1, explanation: '3² + 4² = 9 + 16 = 25, and √25 = 5.' },
  { lessonSlug: 'roman-empire-fall', question: 'When was the last Western Roman Emperor deposed?', options: ['44 BCE', '476 CE', '1066 CE', '1453 CE'], answer: 1, explanation: 'Romulus Augustulus was deposed by Odoacer in 476 CE.' },
  { lessonSlug: 'water-cycle', question: 'What drives the water cycle?', options: ['The moon', 'Solar energy', 'Wind turbines', 'Ocean tides'], answer: 1, explanation: 'The sun provides the energy that evaporates water and drives atmospheric circulation.' },
  { lessonSlug: 'blockchain-simple', question: 'What links each block to the previous one?', options: ['A password', 'A cryptographic hash', 'A URL', 'A serial number'], answer: 1, explanation: 'Each block contains a hash of the previous block, creating an unbreakable chain.' },
  { lessonSlug: 'evolution-natural-selection', question: 'What does natural selection act on?', options: ['Individual effort', 'Heritable variation in traits', 'Technology', 'Weather patterns'], answer: 1, explanation: 'Natural selection acts on heritable trait differences that affect survival and reproduction.' },
  { lessonSlug: 'cognitive-biases', question: 'What is confirmation bias?', options: ['Preferring data supporting existing beliefs', 'Confirming your email', 'Double-checking math', 'Asking for a second opinion'], answer: 0, explanation: 'Confirmation bias leads people to seek information that confirms what they already believe.' },
  { lessonSlug: 'solar-system-scale', question: 'How long does sunlight take to reach Earth?', options: ['Instantly', 'About 8 minutes', 'About 1 hour', 'About 4 years'], answer: 1, explanation: 'Light covers the 150 million km to Earth in about 8 minutes 20 seconds.' },
  { lessonSlug: 'supply-demand', question: 'What happens to price when demand rises and supply stays constant?', options: ['Price drops', 'Price stays the same', 'Price increases', 'Supply rises automatically'], answer: 2, explanation: 'Higher demand with fixed supply creates scarcity, allowing sellers to charge more.' },
  { lessonSlug: 'shakespeare-impact', question: 'Approximately how many words did Shakespeare invent?', options: ['50', '500', '1700+', '10000'], answer: 2, explanation: 'Shakespeare coined over 1,700 words including everyday terms we still use.' },
]

export async function seedData() {
  await Lesson.deleteMany({})
  await Lesson.insertMany(lessons)
  console.log(`Seeded ${lessons.length} lessons`)
  await Quiz.deleteMany({})
  await Quiz.insertMany(quizzes)
  console.log(`Seeded ${quizzes.length} quizzes`)
  await User.deleteMany({ email: { $in: demoProfiles.map((p) => p.email) } })
  await User.insertMany(await Promise.all(demoProfiles.map(async (p) => ({
    email: p.email,
    username: p.username,
    displayName: p.displayName,
    passwordHash: await hashPassword(p.password),
    interests: p.interests,
    age: p.age,
    grade: p.grade,
    xp: p.xp,
    streak: p.streak,
    completedCount: p.completedCount,
    role: p.role as 'user' | 'admin',
    bio: p.bio,
    avatar: '',
    followers: p.followers,
    following: p.following,
  }))))
  console.log(`Seeded ${demoProfiles.length} demo profiles`)
}

if (process.argv[1] && process.argv[1].endsWith('seed.ts')) {
  connectDatabase()
    .then(async () => {
      await seedData()
      await disconnectDatabase()
    })
    .catch((err) => {
      console.error(err)
      process.exit(1)
    })
}